### ISSUE TITLE
这支持语音消息吗？

### ISSUE THREAD

**Issue by ghost** [GeminiLab/OOPLRS#1]
话说我也在写狼人杀，但是不知道实时语音消息该怎么搞，dalao推荐一个库怎么样😂

**Comment by aarkegz** [comment]
我们没有做语音，所以确实不知道。说实话，中文聊天也不支持，因为当时布置任务的时候出现了失误，下层直接用了ASCII，组员又不愿意学Encoding方面的内容，所以就这样了。其实这个项目代码质量一般，算个半成品，课程结束了我们也没有维护。如果这个项目的代码能对您有所帮助，那再好不过了。

**Comment by ghost** [comment]
哈哈，狼人杀这个坑我发现根本填不完。越填坑越多，不过还是语音聊天最难，我现在在参考ffmpeg这个项目的代码，github上有

**Comment by aarkegz** [comment]
谢谢您的关注。很抱歉没能提供更多帮助。
